name: Life in the cities
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60421
title: Life in the cities
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#787878'
    - '#191919'
    - '#3b3b3b'
    - '#bdbdbd'
  brandStrength: 0.6216301969252527
  lightness: 0.07670737593434751
  saturation: 0.1790002090856433
  rhythmicContrast: 0.1313989581540227
purpose: []
