typography_spectrum: 0.60421
color:
  brandColors:
    - '#000000'
    - '#787878'
    - '#191919'
    - '#3b3b3b'
    - '#bdbdbd'
  brandStrength: 0.6216301969252527
  lightness: 0.07670737593434751
  saturation: 0.1790002090856433
  rhythmicContrast: 0.1313989581540227
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Life in the cities
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Life in the cities
description: A photographic urban experience
purpose: []
